### ISSUE TITLE
Bug in symbol.h, symbol struct

### ISSUE THREAD

**Issue by Teufelchen1** [kosmas12/HuffmanCoding#3]
Hi 👋 

If you change the `frequency` type in the `symbol` struct from `uint8_t` to `unsigned int`, the program can actually compress files that are somewhat longer ;)

**Comment by kosmas12** [comment]
@Teufelchen1 The changes mentioned in here, #1 and #2 are all very much appreciated and have been applied with the latest commit. Thanks!
